/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/game/[id]", () => {
  beforeEach(() => {
    // /game/1 is short-circuited server-side in app/api/mlb/game/[gamePk]/route.ts
    // to FIXTURE_LIVE_GAME (NYM @ PHI, TOP 7, 4-2), so no Cypress intercept is
    // required for the page to be hermetic. The 15s poll re-fetches the same
    // payload from the same handler.
    cy.visitAsUser("/game/1");
    cy.get('[data-cy="game-detail"]').should("be.visible");
  });

  it("load /game/1 → hero shows score, LIVE pill, and bases/B-K/OUTS strip", () => {
    cy.get('[data-cy="live-pill"]').should("be.visible").and("contain", "LIVE");
    // Hero score uses a 42px headline with the two team scores separated by en-dash.
    cy.get('[data-cy="hero-headline"]').should("contain", "4").and("contain", "2");
    cy.contains(/TOP\s+7/i).should("be.visible");
    cy.contains("B-K").should("be.visible");
    cy.contains("OUTS").should("be.visible");
    // Each team column renders its W-L beneath the city (FIXTURE_LIVE_GAME has
    // NYM 22-17 and PHI 20-19).
    cy.get('[data-cy="hero-headline"] [data-cy="team-record"]').should("have.length", 2);
    cy.get('[data-cy="hero-headline"]').contains("22 - 17").should("be.visible");
    cy.get('[data-cy="hero-headline"]').contains("20 - 19").should("be.visible");
  });

  it("click Box sub-tab → both teams' lineups and pitching rows render", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="box"]').click();
    // Fixture has 9 batters per team + 1 pitcher away (Senga) + 2 pitchers
    // home (Wheeler, Strahm) = 21 rows. Some are below the fold in the
    // 402×874 viewport so we assert existence, not viewport visibility.
    cy.get('[data-cy="box-player-row"]').should("have.length", 21);
    cy.contains("Kodai Senga").should("exist");
    cy.contains("Zack Wheeler").should("exist");
    cy.contains("Matt Strahm").should("exist");
  });

  it("click Spray sub-tab → default batter card renders; picker switches the chart", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="spray"]').click();
    // Default falls back to most-recent batter in spray array (Lindor is first
    // in the fixture's recency-sorted list).
    cy.contains("Lindor · Spray Chart").should("be.visible");
    cy.get('[data-cy="batter-picker"]').select("660271"); // Pete Alonso
    cy.contains("Alonso · Spray Chart").should("be.visible");
    cy.contains("Lindor · Spray Chart").should("not.exist");
  });

  it("seed user with pitchByPitch:false → Pitches sub-tab is absent", () => {
    cy.visitAsUser("/game/1", "user-no-pitches");
    cy.get('[data-cy="game-detail"]').should("be.visible");
    cy.get('[data-cy="sub-tab"][data-cy-tab="pitches"]').should("not.exist");
    // Spray remains independent of the pref.
    cy.get('[data-cy="sub-tab"][data-cy-tab="spray"]').should("exist");
  });

  it("scroll content area → hero collapses to 0 height and score chips appear", () => {
    // Pre-scroll: hero is its measured natural height; chips are hidden.
    cy.get('[data-cy="hero-headline"]').should("have.css", "opacity", "1");
    cy.get('[data-cy="score-chip"][data-cy-side="away"]').should("not.be.visible");
    // Scrolling past the 15px threshold flips `scrolled` → `condensed`.
    cy.get('[data-cy="game-detail-scroll"]').scrollTo(0, 200);
    cy.get('[data-cy="hero-headline"]').should("have.css", "opacity", "0");
    cy.get('[data-cy="score-chip"][data-cy-side="away"]').should("be.visible");
    cy.get('[data-cy="score-chip"][data-cy-side="home"]').should("be.visible");
  });

  it("click a Box lineup row → navigates to /player/[id]", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="box"]').click();
    // Francisco Lindor (596019) is in the away lineup in the fixture.
    cy.get('[data-cy="box-player-row"][data-cy-player-id="596019"]').click();
    cy.location("pathname").should("eq", "/player/596019");
  });
});
