/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/game/[id]", () => {
  beforeEach(() => {
    // /game/1 is short-circuited server-side in app/api/mlb/game/[gamePk]/route.ts
    // to FIXTURE_LIVE_GAME (NYM @ PHI, TOP 7, 4-2), so no Cypress intercept is
    // required for the page to be hermetic. The 15s poll re-fetches the same
    // payload from the same handler.
    cy.visitAsUser("/game/1");
    cy.get('[data-cy="game-detail"]').should("be.visible");
  });

  it("load /game/1 → hero shows score, LIVE pill, and bases/B-K/OUTS strip", () => {
    cy.get('[data-cy="live-pill"]').should("be.visible").and("contain", "LIVE");
    // Hero score uses a 42px headline with the two team scores separated by en-dash.
    cy.get('[data-cy="hero-headline"]').should("contain", "4").and("contain", "2");
    cy.contains(/TOP\s+7/i).should("be.visible");
    cy.contains("B-K").should("be.visible");
    cy.contains("OUTS").should("be.visible");
    // Each team column renders its W-L beneath the city (FIXTURE_LIVE_GAME has
    // NYM 22-17 and PHI 20-19).
    cy.get('[data-cy="hero-headline"] [data-cy="team-record"]').should("have.length", 2);
    cy.get('[data-cy="hero-headline"]').contains("22 - 17").should("be.visible");
    cy.get('[data-cy="hero-headline"]').contains("20 - 19").should("be.visible");
  });

  it("click Box sub-tab → both teams' lineups and pitching rows render", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="box"]').click();
    // Fixture has 9 batters per team + 1 pitcher away (Senga) + 2 pitchers
    // home (Wheeler, Strahm) = 21 rows. Some are below the fold in the
    // 402×874 viewport so we assert existence, not viewport visibility.
    cy.get('[data-cy="box-player-row"]').should("have.length", 21);
    cy.contains("Kodai Senga").should("exist");
    cy.contains("Zack Wheeler").should("exist");
    cy.contains("Matt Strahm").should("exist");
  });

  it("click Spray sub-tab → default batter card renders; picker switches the chart", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="spray"]').click();
    // Default falls back to most-recent batter in spray array (Lindor is first
    // in the fixture's recency-sorted list).
    cy.contains("Lindor · Spray Chart").should("be.visible");
    cy.get('[data-cy="batter-picker"]').select("660271"); // Pete Alonso
    cy.contains("Alonso · Spray Chart").should("be.visible");
    cy.contains("Lindor · Spray Chart").should("not.exist");
  });

  it("seed user with pitchByPitch:false → Pitches sub-tab is absent", () => {
    cy.visitAsUser("/game/1", "user-no-pitches");
    cy.get('[data-cy="game-detail"]').should("be.visible");
    cy.get('[data-cy="sub-tab"][data-cy-tab="pitches"]').should("not.exist");
    // Spray remains independent of the pref.
    cy.get('[data-cy="sub-tab"][data-cy-tab="spray"]').should("exist");
  });

  it("scroll content area → hero collapses to 0 height and score chips appear", () => {
    // Pre-scroll: hero is its measured natural height; chips are hidden.
    cy.get('[data-cy="hero-headline"]').should("have.css", "opacity", "1");
    cy.get('[data-cy="score-chip"][data-cy-side="away"]').should("not.be.visible");
    // Scrolling past the 15px threshold flips `scrolled` → `condensed`.
    cy.get('[data-cy="game-detail-scroll"]').scrollTo(0, 200);
    cy.get('[data-cy="hero-headline"]').should("have.css", "opacity", "0");
    cy.get('[data-cy="score-chip"][data-cy-side="away"]').should("be.visible");
    cy.get('[data-cy="score-chip"][data-cy-side="home"]').should("be.visible");
  });

  it("click Plays sub-tab → Scoring filter narrows list to scoring plays only", () => {
    // Generated by Cypress Author on 2026-05-16.
    // FIXTURE_LIVE_GAME has 6 plays; 3 carry a `score` field (Alonso 2B "4-2",
    // Nimmo HR "3-2", Schwarber HR "2-2") and qualify as scoring plays.
    cy.get('[data-cy="sub-tab"][data-cy-tab="plays"]').click();
    cy.get('[data-cy="play-row"]').should("have.length", 6);
    // Default is "All" selected.
    cy.get('[data-cy="plays-filter-option"][data-cy-filter="all"]').should(
      "have.attr",
      "aria-pressed",
      "true",
    );
    cy.get('[data-cy="plays-filter-option"][data-cy-filter="scoring"]').click();
    cy.get('[data-cy="play-row"]').should("have.length", 3);
    cy.contains("Pete Alonso doubles").should("exist");
    cy.contains("Brandon Nimmo homers").should("exist");
    cy.contains("Kyle Schwarber homers").should("exist");
    cy.contains("Trea Turner strikes out").should("not.exist");
    // Toggle back restores the full list.
    cy.get('[data-cy="plays-filter-option"][data-cy-filter="all"]').click();
    cy.get('[data-cy="play-row"]').should("have.length", 6);
  });

  it("click a Box lineup row → navigates to /player/[id]", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="box"]').click();
    // Francisco Lindor (596019) is in the away lineup in the fixture.
    cy.get('[data-cy="box-player-row"][data-cy-player-id="596019"]').click();
    cy.location("pathname").should("eq", "/player/596019");
  });

  // Generated by Cypress Author on 2026-07-07.
  it("strike zone drawn from the catcher's view → right-handed batter marker sits left of the zone center", () => {
    // FIXTURE_LIVE_GAME's current batter (Mark Vientos) is right-handed. From
    // the catcher's perspective a RHB stands in the third-base box, i.e. the
    // LEFT side of the zone, so the "RHB" marker must render left of the
    // strike-zone SVG's horizontal center — not on the right.
    cy.get('[data-cy="batter-hand-indicator"]')
      .should("have.attr", "data-cy-hand", "R")
      .and("contain", "RHB")
      .then(($label) => {
        const label = $label[0].getBoundingClientRect();
        const svg = ($label[0] as unknown as SVGGraphicsElement).ownerSVGElement!.getBoundingClientRect();
        const labelCenter = label.left + label.width / 2;
        const svgCenter = svg.left + svg.width / 2;
        expect(labelCenter, "RHB marker sits left of zone center").to.be.lessThan(svgCenter);
      });
  });

  // Generated by Cypress Author on 2026-07-07.
  it("click a Pitches-tab pitcher summary name → navigates to that pitcher's /player/[id]", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="pitches"]').click();
    // Fixture pitchers with usage: Senga (605135) away, Wheeler (554430) &
    // Strahm (669373) home — each summary card's name is a link.
    cy.get('[data-cy="pitcher-usage-name"]').should("have.length", 3);
    cy.get('[data-cy="pitcher-usage-name"][data-cy-player-id="605135"]')
      .should("contain", "Kodai Senga")
      .click();
    cy.location("pathname").should("eq", "/player/605135");
  });
});
