/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/leaders", () => {
  beforeEach(() => {
    // Single fixture covers all four categories the spec exercises (AVG, HR,
    // ERA, FPCT). The route caches client-side, but Cypress sees only the
    // first request each visit — which is what we wait on.
    cy.intercept("GET", "/api/mlb/leaders*", { fixture: "leaders.json" }).as("leaders");
    cy.visitAsUser("/leaders");
    cy.wait("@leaders");
  });

  it("load /leaders → default Batting/AVG view shows the first page of leader rows", () => {
    cy.get('[data-cy="leaders-screen"]').should("be.visible");
    // Default is hitting group / AVG metric. PAGE_SIZE is 10; fixture has 12,
    // so the first page renders 10 rows and Load More is available.
    cy.get('[data-cy="group-tab"][data-cy-group="hitting"]').should("have.attr", "aria-selected", "true");
    cy.get('[data-cy="leader-row"]').should("have.length", 10);
    cy.get('[data-cy="load-more"]').should("be.visible");
  });

  it("click Pitching group tab → metric pills switch and ERA leader list renders", () => {
    cy.get('[data-cy="group-tab"][data-cy-group="pitching"]').click();
    cy.get('[data-cy="metric-pill"][data-cy-metric="ERA"]').should("be.visible");
    // Default metric for pitching is ERA; fixture has 12 ERA rows.
    cy.get('[data-cy="leader-row"]').should("have.length", 10);
    cy.contains("Earned Run Avg").should("be.visible");
  });

  it("click HR metric pill → list re-renders for that category", () => {
    cy.get('[data-cy="metric-pill"][data-cy-metric="HR"]').click();
    cy.contains("Home Runs").should("be.visible");
    // Fixture has 5 HR rows; under PAGE_SIZE so no Load More.
    cy.get('[data-cy="leader-row"]').should("have.length", 5);
    cy.get('[data-cy="load-more"]').should("not.exist");
  });

  it("click Load More → next page of rows is appended", () => {
    cy.get('[data-cy="leader-row"]').should("have.length", 10);
    cy.get('[data-cy="load-more"]').click();
    // Fixture has 12 AVG rows; after one click we should see all 12.
    cy.get('[data-cy="leader-row"]').should("have.length", 12);
    cy.get('[data-cy="load-more"]').should("not.exist");
  });

  it("click a leader row → navigates to /player/[id]", () => {
    cy.get('[data-cy="leader-row"][data-cy-player-id="596019"]').click();
    cy.location("pathname").should("eq", "/player/596019");
  });
});
