/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-13.

describe("/login", () => {
  beforeEach(() => {
    // Use visitAsAnonymous so neither the guest profile nor the nudge-suppress
    // key are seeded — /login should be reachable directly without any prior
    // state, and the server-side gate is "no Supabase session", which is
    // satisfied by default in a fresh test browser (no auth cookies).
    cy.visitAsAnonymous("/login");
  });

  it("load /login → form renders with email, password, and continue-as-guest fallback", () => {
    cy.get("input[type=email]").should("be.visible");
    cy.get("input[type=password]").should("be.visible");
    cy.contains("button", /sign in/i).should("be.visible");
    // Continue-as-guest is now a button (was a Link) — it triggers a
    // recaptcha check via a server action before navigating to /scores.
    cy.get('[data-cy="continue-as-guest"]').should("be.visible").and("have.text", "Continue as guest");
  });

  it("starts in sign-in mode → 'Forgot?' link is visible, 'Create one' toggle is available", () => {
    // Sign-in mode only — the password label houses the forgot link.
    cy.get('[data-cy="forgot-password-link"]')
      .should("be.visible")
      .and("have.attr", "href", "/forgot-password");
    cy.contains("button", /create one/i).should("be.visible");
  });

  it("toggle to sign-up mode → 'Forgot?' link disappears and copy flips", () => {
    cy.contains("button", /create one/i).click();
    // Submit button label becomes "Create account" — the unambiguous signal
    // of sign-up mode. (The header copy uses <br/> between "your" and
    // "profile" so cy.contains with a whitespace regex doesn't match the
    // text node directly — button text is sturdier.)
    cy.contains("button", /create account/i).should("be.visible");
    // The forgot link is sign-in-mode only.
    cy.get('[data-cy="forgot-password-link"]').should("not.exist");
    // And reverse-toggle should be available.
    cy.contains("button", /sign in/i).should("be.visible");
  });

  it("password visibility toggle → input type flips between password and text", () => {
    const PWD = "hunter22";
    cy.get("input[type=password]").as("pwd").type(PWD);
    // Default: hidden — input is type=password
    cy.get("@pwd").should("have.attr", "type", "password");
    // Click "Show" → type becomes text
    cy.get('[data-cy="password-visibility-toggle"]').click();
    cy.get("input[autocomplete='current-password']")
      .should("have.attr", "type", "text")
      .and("have.value", PWD);
    // Click "Hide" → back to type=password
    cy.get('[data-cy="password-visibility-toggle"]').click();
    cy.get("input[autocomplete='current-password']").should("have.attr", "type", "password");
  });

  it("submit disabled until email is non-empty AND password is at least 6 chars", () => {
    const submit = () => cy.contains("button", /sign in/i);
    // Empty form → disabled
    submit().should("be.disabled");
    // Email only → still disabled
    cy.get("input[type=email]").type("test@example.com");
    submit().should("be.disabled");
    // Email + short password → still disabled
    cy.get("input[type=password]").type("12345");
    submit().should("be.disabled");
    // Email + 6+ char password → enabled
    cy.get("input[type=password]").type("6");
    submit().should("not.be.disabled");
  });

  it("click Continue as guest → routes to /scores", () => {
    cy.get('[data-cy="continue-as-guest"]').click();
    cy.location("pathname").should("eq", "/scores");
  });
});
