/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-13.

describe("first-run onboarding", () => {
  beforeEach(() => {
    // Anonymous visitors land on the scoreboard route under the shell, with
    // the onboarding overlay opening on top. The /scores page renders behind
    // the overlay and fetches scoreboard data, so we mock it.
    cy.mockScoreboard();
    cy.visitAsAnonymous("/scores");
  });

  it("anonymous visitor → splash renders both choices + the sign-in fallback link", () => {
    cy.get('[data-cy="onboarding-splash"]').should("be.visible");
    // Use `have.text` for exact match — chai's `contain` does substring on
    // strings only, not regex (the regex form silently fails to match).
    cy.get('[data-cy="splash-signup"]').should("be.visible").and("have.text", "Create a profile");
    cy.get('[data-cy="splash-guest"]').should("be.visible").and("have.text", "Continue as guest");
    cy.get('[data-cy="onboarding-signin-link"]').should("be.visible");
  });

  it("click 'Create a profile' on the splash → routes to /login", () => {
    cy.get('[data-cy="splash-signup"]').click();
    cy.location("pathname").should("eq", "/login");
  });

  it("click sign-in fallback link on the splash → routes to /login", () => {
    cy.get('[data-cy="onboarding-signin-link"]').click();
    cy.location("pathname").should("eq", "/login");
  });

  it("guest path: splash → name → teams → /scores with localStorage populated", () => {
    // Step 0: pick guest.
    cy.get('[data-cy="splash-guest"]').click();
    // Step 1: name entry. The "What's your name?" heading inserts a <br>
    // between "your" and "name" with no whitespace, so we use the input's
    // placeholder as a sturdier signal that we're on this step.
    cy.get("input[placeholder='Your name']").should("be.visible").type("Tester");
    cy.contains("button", /^continue$/i).click();
    // Step 2: team picker. The "Follow your teams" heading inserts a <br>
    // with no whitespace (same as step 1), so we use the search input as
    // the step-2 signal — it's unique to this step.
    cy.get("input[placeholder='Search teams']").should("be.visible");
    // Pick two AL teams by their city text (cy.contains returns the first
    // DOM match; AL list is alphabetized so "Boston" → BOS, "New York" → NYY).
    cy.contains("Boston").click();
    cy.contains("New York").click();
    // Finish.
    cy.contains("button", /continue to scores/i).click();
    // Overlay gone (the unique "Continue to scores" button is the cleanest
    // signal — the splash data-cy belongs to step 0, not step 2).
    cy.contains("button", /continue to scores/i).should("not.exist");
    cy.get('[data-cy="scores-screen"]').should("be.visible");
    // localStorage should now have a guest profile that mirrors what the
    // user just entered.
    cy.window().then((win) => {
      const raw = win.localStorage.getItem("dl_user");
      expect(raw, "dl_user is written after onboarding").to.be.a("string");
      const profile = JSON.parse(raw as string);
      expect(profile.name).to.equal("Tester");
      expect(profile.follows).to.include("NYY");
      expect(profile.follows).to.include("BOS");
      expect(profile.onboarded).to.equal(true);
    });
  });

});

describe("returning user (seeded guest profile)", () => {
  beforeEach(() => {
    cy.mockScoreboard();
    cy.visitAsUser("/scores");
  });

  it("onboarding overlay does not open — gate sees onboarded=true", () => {
    // visitAsUser seeds the profile + the nudge-suppress timestamp, so the
    // shell's onboarding gate evaluates the user as a guest with
    // onboarded=true and the overlay never mounts.
    cy.get('[data-cy="onboarding-splash"]').should("not.exist");
    cy.contains(/your name\?/i).should("not.exist");
    cy.get('[data-cy="scores-screen"]').should("be.visible");
  });

  it("guest nudge banner is suppressed by the test seed", () => {
    // visitAsUser seeds `dl_guest_nudge_until` to a far-future timestamp so
    // the banner never appears during tests — confirming the suppression
    // works for all the existing specs that use visitAsUser.
    cy.get('[data-cy="guest-nudge-banner"]').should("not.exist");
  });
});
