/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/player/[id]", () => {
  beforeEach(() => {
    // PlayerDetail's four sub-tabs each hit a different endpoint. Stub them all
    // up-front in beforeEach so any sub-tab the test exercises has a deterministic
    // response and so individual tests stay independent.
    cy.intercept("GET", "/api/mlb/player/596019",                { fixture: "player-detail.json" }).as("player");
    cy.intercept("GET", "/api/mlb/player/596019/splits*",        { fixture: "player-splits-hitting.json" }).as("splits");
    cy.intercept("GET", "/api/mlb/player/596019/gamelog*",       { fixture: "player-gamelog-hitting.json" }).as("gamelog");
    cy.intercept("GET", "/api/mlb/player/596019/history*",       { fixture: "player-history-hitting.json" }).as("history");
    cy.visitAsUser("/player/596019");
    cy.wait("@player");
  });

  it("load /player/596019 → hero shows name + team chip; Season tab is active by default", () => {
    cy.get('[data-cy="player-detail"]').should("be.visible");
    cy.contains("Francisco Lindor").should("be.visible");
    cy.get('[data-cy="player-team-chip"]').should("contain", "Mets");
    cy.get('[data-cy="sub-tab"][data-cy-tab="season"]').should("have.class", "font-bold");
    // Season tab renders four headline tiles (AVG, HR, RBI, OPS for a hitter).
    cy.get('[data-cy="headline-tile"]').should("have.length", 4);
  });

  it("click Splits sub-tab → splits rows render with vR / vL labels", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="splits"]').click();
    cy.wait("@splits");
    cy.get('[data-cy="splits-row"]').should("have.length", 7);
    cy.contains("vs RHP").should("be.visible");
    cy.contains("vs LHP").should("be.visible");
    cy.contains("RISP").should("be.visible");
  });

  it("click Gamelog sub-tab → gamelog rows render in hitter columns", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="gamelog"]').click();
    cy.wait("@gamelog");
    cy.get('[data-cy="gamelog-row"]').should("have.length", 8);
    // Hitter mode column header (the H/AB column is unique to hitter view).
    cy.contains("H/AB").should("be.visible");
  });

  it("click History sub-tab → career tiles, year rows, and highlights render", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="history"]').click();
    cy.wait("@history");
    // 5 fixture years
    cy.get('[data-cy="history-year"]').should("have.length", 5);
    cy.contains("Career · 11 seasons").should("be.visible");
    cy.contains("All-Star").should("be.visible");
    cy.contains("Gold Glove").should("be.visible");
  });

  it("click team chip in hero → navigates to /team/NYM", () => {
    cy.get('[data-cy="player-team-chip"]').click();
    cy.location("pathname").should("eq", "/team/NYM");
  });
});
