/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/player/[id]", () => {
  beforeEach(() => {
    // PlayerDetail's four sub-tabs each hit a different endpoint. Stub them all
    // up-front in beforeEach so any sub-tab the test exercises has a deterministic
    // response and so individual tests stay independent.
    cy.intercept("GET", "/api/mlb/player/596019",                { fixture: "player-detail.json" }).as("player");
    cy.intercept("GET", "/api/mlb/player/596019/splits*",        { fixture: "player-splits-hitting.json" }).as("splits");
    cy.intercept("GET", "/api/mlb/player/596019/gamelog*",       { fixture: "player-gamelog-hitting.json" }).as("gamelog");
    cy.intercept("GET", "/api/mlb/player/596019/history*",       { fixture: "player-history-hitting.json" }).as("history");
    // The Season tab is mounted on first paint and fetches /api/mlb/players
    // for the compare picker's directory. Register the intercept up here so
    // the request is captured before it fires — otherwise tests in the
    // comparison context race the initial paint.
    cy.intercept("GET", "/api/mlb/players*",                     { fixture: "active-players.json" }).as("directory");
    cy.visitAsUser("/player/596019");
    cy.wait("@player");
  });

  it("load /player/596019 → hero shows name + team chip; Season tab is active by default", () => {
    cy.get('[data-cy="player-detail"]').should("be.visible");
    cy.contains("Francisco Lindor").should("be.visible");
    cy.get('[data-cy="player-team-chip"]').should("contain", "Mets");
    cy.get('[data-cy="sub-tab"][data-cy-tab="season"]').should("have.class", "font-bold");
    // Season tab renders four headline tiles (AVG, HR, RBI, OPS for a hitter).
    cy.get('[data-cy="headline-tile"]').should("have.length", 4);
  });

  it("Season tab → splits section renders inline with vR / vL labels", () => {
    // Splits used to be their own sub-tab; they now appear as a sibling
    // section inside the Season tab. The /splits endpoint is fetched on
    // first paint of the Season tab. The section sits below the Batting
    // card, so on the 402×874 mobile viewport the rows land below the
    // fold — assert via `exist`, not `be.visible`.
    cy.wait("@splits");
    cy.get('[data-cy="splits-section"]').should("exist");
    cy.get('[data-cy="splits-row"]').should("have.length", 7);
    cy.contains("vs RHP").should("exist");
    cy.contains("vs LHP").should("exist");
    // The dedicated Splits sub-tab is gone — replaced by the v. League tab.
    cy.get('[data-cy="sub-tab"][data-cy-tab="splits"]').should("not.exist");
    cy.get('[data-cy="sub-tab"][data-cy-tab="vsleague"]').should("exist");
  });

  it("click Gamelog sub-tab → gamelog rows render in hitter columns", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="gamelog"]').click();
    cy.wait("@gamelog");
    cy.get('[data-cy="gamelog-row"]').should("have.length", 8);
    // Hitter mode column header (the H/AB column is unique to hitter view).
    cy.contains("H/AB").should("be.visible");
    // Hitter columns are DATE | OPP | H/AB | H | HR | RBI | K | BB. Assert
    // positionally rather than by text — "K" and "BB" as bare strings match
    // too much elsewhere on the page to be safe selectors.
    // Newest fixture game (5/12): 1-for-4 with 2 K and 1 BB.
    cy.get('[data-cy="gamelog-row"]').first().children().as("cells");
    cy.get("@cells").should("have.length", 8);
    cy.get("@cells").eq(2).should("have.text", "1-4"); // H/AB
    cy.get("@cells").eq(5).should("have.text", "0");   // RBI
    cy.get("@cells").eq(6).should("have.text", "2");   // K
    cy.get("@cells").eq(7).should("have.text", "1");   // BB
  });

  it("click History sub-tab → career tiles, year rows, and highlights render", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="history"]').click();
    cy.wait("@history");
    // 5 fixture years
    cy.get('[data-cy="history-year"]').should("have.length", 5);
    cy.contains("Career · 11 seasons").should("be.visible");
    cy.contains("All-Star").should("be.visible");
    cy.contains("Gold Glove").should("be.visible");
  });

  it("click team chip in hero → navigates to /team/NYM", () => {
    cy.get('[data-cy="player-team-chip"]').click();
    cy.location("pathname").should("eq", "/team/NYM");
  });

  // Added 2026-05-15 for the Season-tab comparison feature.
  context("Season tab → compare", () => {
    beforeEach(() => {
      // `@directory` (the /api/mlb/players intercept) is registered in the
      // outer beforeEach so the initial-paint request is captured. The
      // compare-target intercept only fires after the user picks Alonso.
      cy.intercept("GET", "/api/mlb/player/660271", { fixture: "player-detail-alonso.json" }).as("compare");
      cy.wait("@directory");
    });

    it("focus picker → tray shows hitters only (pitchers filtered out for hitter focal player)", () => {
      cy.get('[data-cy="compare-picker"] [data-cy="compare-input"]').focus();
      cy.get('[data-cy="compare-tray"]').should("be.visible");
      // Lindor is the focal player (hitter); the tray should include other hitters
      // and exclude pitchers like Senga (605135) and Ottavino (657277).
      cy.get('[data-cy="compare-option"][data-cy-id="660271"]').should("exist");
      cy.get('[data-cy="compare-option"][data-cy-id="624415"]').should("exist");
      cy.get('[data-cy="compare-option"][data-cy-id="605135"]').should("not.exist");
      cy.get('[data-cy="compare-option"][data-cy-id="657277"]').should("not.exist");
      // Self-exclusion: Lindor himself is not in the tray.
      cy.get('[data-cy="compare-option"][data-cy-id="596019"]').should("not.exist");
    });

    it("type 'alonso' → tray filters to Pete Alonso", () => {
      cy.get('[data-cy="compare-picker"] [data-cy="compare-input"]').type("alonso");
      cy.get('[data-cy="compare-option"]').should("have.length", 1);
      cy.get('[data-cy="compare-option"][data-cy-id="660271"]').should("contain", "Pete Alonso");
    });

    it("select Alonso → ?compare=660271 in URL and Batting table grows a third column", () => {
      cy.get('[data-cy="compare-picker"] [data-cy="compare-input"]').type("alonso");
      cy.get('[data-cy="compare-option"][data-cy-id="660271"]').click();
      cy.wait("@compare");
      cy.location("search").should("contain", "compare=660271");
      cy.get('[data-cy="stat-primary-value"]').should("exist");
      cy.get('[data-cy="stat-compare-value"]').should("exist");
    });

    it("clear → URL drops ?compare and table collapses", () => {
      cy.get('[data-cy="compare-picker"] [data-cy="compare-input"]').type("alonso");
      cy.get('[data-cy="compare-option"][data-cy-id="660271"]').click();
      cy.wait("@compare");
      cy.get('[data-cy="compare-clear"]').click();
      cy.location("search").should("not.contain", "compare=");
      cy.get('[data-cy="stat-compare-value"]').should("not.exist");
    });

    it("deep link /player/596019?compare=660271 → comparison restored on load", () => {
      cy.visitAsUser("/player/596019?compare=660271");
      cy.wait("@player");
      cy.wait("@compare");
      cy.get('[data-cy="stat-compare-value"]').should("exist");
    });
  });

  // Rewritten 2026-06-12: the v. League tab now renders percentile sliders
  // backed by analytics.player_batting_percentiles (one per rate category —
  // AVG, OBP, SLG, OPS, BB%, K%, BABIP) instead of the old league-average
  // delta bars. wRC+ is in the table but still null, so it isn't surfaced.
  // Lindor (596019) is the focal hitter; player-batting-percentiles.json
  // supplies a row whose ranks span hot (SLG 97th) to cool (BABIP 26th).
  context("v. League sub-tab", () => {
    beforeEach(() => {
      cy.intercept("GET", "/api/analytics/player-batting-percentiles/596019*", {
        fixture: "player-batting-percentiles.json",
      }).as("percentiles");
    });

    it("guest views v. League tab → sign-up CTA shows and the percentile endpoint is never fetched", () => {
      cy.get('[data-cy="sub-tab"][data-cy-tab="vsleague"]').click();
      cy.get('[data-cy="vsleague-signup-prompt"]').should("be.visible");
      cy.get('[data-cy="vsleague-signup-cta"]')
        .should("have.attr", "href")
        .and("include", "/login?redirect=");
      cy.get('[data-cy="vsleague-signin-link"]').should("be.visible");
      // Auth gate at the component too — no percentile fetch should fire.
      cy.get('[data-cy="vsleague-chart"]').should("not.exist");
      cy.get("@percentiles.all").should("have.length", 0);
    });

    it("authenticated viewer opens ?tab=vsleague → one percentile slider renders per rate category", () => {
      cy.visitAsAuthenticatedUser("/player/596019?tab=vsleague");
      cy.wait("@player");
      cy.wait("@percentiles");

      cy.get('[data-cy="vsleague-chart"]').should("be.visible");

      // Seven categories in the fixture: AVG, OBP, SLG, OPS, BB%, K%, BABIP.
      // wRC+ is present in the row but null, so it must not render a slider.
      cy.get('[data-cy="percentile-row"]').should("have.length", 7);
      cy.get('[data-cy="percentile-row"][data-cy-stat="wrc_plus"]').should("not.exist");

      // AVG row: raw .318 with a 92nd-percentile rank.
      const avg = () => cy.get('[data-cy="percentile-row"][data-cy-stat="avg"]');
      avg().find('[data-cy="percentile-value"]').should("contain", "318");
      avg().find('[data-cy="percentile-rank"]').should("contain", "92nd");

      // K% row: raw 18.5% with a 60th-percentile rank.
      const k = () => cy.get('[data-cy="percentile-row"][data-cy-stat="k_pct"]');
      k().find('[data-cy="percentile-value"]').should("contain", "18.5%");
      k().find('[data-cy="percentile-rank"]').should("contain", "60th");

      // BB% row: raw 10.5% with a 65th-percentile rank.
      const bb = () => cy.get('[data-cy="percentile-row"][data-cy-stat="bb_pct"]');
      bb().find('[data-cy="percentile-value"]').should("contain", "10.5%");
      bb().find('[data-cy="percentile-rank"]').should("contain", "65th");

      // BABIP row: raw .264 with a cool 26th-percentile rank.
      const babip = () => cy.get('[data-cy="percentile-row"][data-cy-stat="babip"]');
      babip().find('[data-cy="percentile-value"]').should("contain", "264");
      babip().find('[data-cy="percentile-rank"]').should("contain", "26th");

      // Sign-up prompt must not coexist with the chart.
      cy.get('[data-cy="vsleague-signup-prompt"]').should("not.exist");
    });
  });
});

// Added 2026-05-27 for the Pitches sub-tab arsenal visualizations. Senga
// (605135) is the pitcher fixture; the chart components are auth-gated so
// these tests exercise both the guest sign-up prompt and the authenticated
// chart render path.
describe("/player/[id] → Pitches tab (arsenal visualizations)", () => {
  beforeEach(() => {
    cy.intercept("GET", "/api/mlb/player/605135",                  { fixture: "player-detail-senga.json" }).as("player");
    cy.intercept("GET", "/api/mlb/players*",                       { fixture: "active-players.json" }).as("directory");
    cy.intercept("GET", "/api/analytics/pitcher-arsenal/605135*",  { fixture: "pitcher-arsenal-senga.json" }).as("arsenal");
    cy.intercept("GET", "/api/analytics/league-pitch-summary*",    { fixture: "league-pitch-summary.json" }).as("league");
  });

  it("guest viewer → Pitches sub-tab shows sign-up prompt with redirect link to /login", () => {
    cy.visitAsUser("/player/605135");
    cy.wait("@player");
    cy.get('[data-cy="sub-tab"][data-cy-tab="pitches"]').click();
    cy.get('[data-cy="pitches-signup-prompt"]').should("be.visible");
    cy.get('[data-cy="pitches-signup-cta"]')
      .should("have.attr", "href")
      .and("include", "/login?redirect=");
    cy.get('[data-cy="pitches-signin-link"]').should("be.visible");
    // Analytics endpoints must never be called when the user isn't authed —
    // the gate is at the component, not just the API.
    cy.get('[data-cy="pitch-arsenal-chart"]').should("not.exist");
  });

  it("authenticated viewer + ?tab=pitches → metric pills, arsenal bubbles, legend, and vs-league bars all render", () => {
    cy.visitAsAuthenticatedUser("/player/605135?tab=pitches");
    cy.wait("@player");
    cy.wait("@arsenal");
    cy.wait("@league");

    // All seven metric pills present, Usage selected by default.
    cy.get('[data-cy="pitch-metric-pill"]').should("have.length", 7);
    cy.get('[data-cy="pitch-metric-pill"][data-cy-metric="usage_pct"]')
      .should("have.attr", "aria-selected", "true");

    // Arsenal bubble chart + heading reflects the default metric.
    cy.get('[data-cy="pitch-arsenal-chart"]').should("be.visible");
    cy.get('[data-cy="pitch-arsenal-heading"]').should("contain", "Pitch Usage");

    // One legend row per pitch in the fixture (FF, FS, CU, SL, CH).
    cy.get('[data-cy="pitch-arsenal-row"]').should("have.length", 5);
    // Legend sorts by magnitude desc — Usage: FF (38.2%) leads.
    cy.get('[data-cy="pitch-arsenal-row"]').first().should("contain", "FF").and("contain", "38.2%");

    // Pitcher-vs-league chart with one diverging row per matched pitch.
    // `exist` (not `be.visible`) because the chart sits below the legend
    // table — on the 402×874 mobile viewport it lands below the fold.
    cy.get('[data-cy="pitcher-vs-league-chart"]').should("exist");
    cy.get('[data-cy="pitcher-vs-league-heading"]').should("contain", "Pitch Usage vs League Average");
    cy.get('[data-cy="vs-league-row"]').should("have.length", 5);
  });

  it("click the Velo metric pill → headings, legend values, and sort order all switch to velocity", () => {
    cy.visitAsAuthenticatedUser("/player/605135?tab=pitches");
    cy.wait("@player");
    cy.wait("@arsenal");
    cy.wait("@league");

    cy.get('[data-cy="pitch-metric-pill"][data-cy-metric="avg_start_speed"]').click();
    cy.get('[data-cy="pitch-metric-pill"][data-cy-metric="avg_start_speed"]')
      .should("have.attr", "aria-selected", "true");

    cy.get('[data-cy="pitch-arsenal-heading"]').should("contain", "Average Velocity");
    cy.get('[data-cy="pitcher-vs-league-heading"]').should("contain", "Average Velocity vs League Average");

    // Legend re-sorts by velocity desc — FF (96.4 mph) is now the top row
    // and its value renders with the mph unit.
    cy.get('[data-cy="pitch-arsenal-row"]').first().should("contain", "FF").and("contain", "96.4 mph");
  });
});
