/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/schedule", () => {
  beforeEach(() => {
    // Aliases live in beforeEach (Cypress clears them between tests), and
    // the intercept lands before the visit so the cached useApi fetch is
    // satisfied on first render.
    cy.intercept("GET", "/api/mlb/schedule*", { fixture: "schedule.json" }).as("schedule");
    cy.visitAsUser("/schedule");
    cy.wait("@schedule");
  });

  it("load /schedule → games render grouped by date with a TODAY badge", () => {
    cy.get('[data-cy="schedule-screen"]').should("be.visible");
    // The fixture's `today` (2026-05-12) drives the TODAY badge and is the
    // earliest date shown when "Show past games" is off (default).
    cy.contains("TODAY").should("be.visible");
    // Default scope is League, past hidden. Fixture has 7 games on/after today
    // (4 on 2026-05-12 plus 3 on 2026-05-13).
    cy.get('[data-cy="schedule-game-row"]').should("have.length", 7);
  });

  it("click Following scope → only games involving followed teams remain", () => {
    cy.get('[data-cy="scope-tab"][data-cy-scope="follow"]').click();
    // The user fixture follows NYM and PHI. From today onward the fixture has
    // game id=1 (NYM @ PHI) and id=9007 (PHI @ NYM). Two games total.
    cy.get('[data-cy="schedule-game-row"]').should("have.length", 2);
    cy.get('[data-cy="schedule-game-row"][data-cy-game-id="1"]').should("exist");
    cy.get('[data-cy="schedule-game-row"][data-cy-game-id="9007"]').should("exist");
  });

  it("click Show past games → past-dated games appear above today", () => {
    cy.get('[data-cy="show-past-toggle"]').click();
    // Now we also see the three 2026-05-11 games (ids 9001/9002/9003) plus
    // the 7 already visible = 10 total.
    cy.get('[data-cy="schedule-game-row"]').should("have.length", 10);
    cy.get('[data-cy="schedule-game-row"][data-cy-game-id="9001"]').should("exist");
  });

  it("click a game row → navigates to /game/[id]", () => {
    cy.get('[data-cy="schedule-game-row"][data-cy-game-id="1"]').click();
    cy.location("pathname").should("eq", "/game/1");
  });

  it("open By-team picker and pick a team → schedule filters to that team", () => {
    // "By team" without a current selection opens the picker rather than
    // applying the scope directly.
    cy.get('[data-cy="scope-tab"][data-cy-scope="team"]').click();
    cy.get('[data-cy="team-picker"]').should("be.visible");
    cy.get('[data-cy="team-picker"]').contains("Mets").click();
    // Picker closes and scope becomes "team" filtered to NYM. Three NYM games
    // from today onward in the fixture: 1 (today vs PHI) and 9007 (5-13 vs PHI).
    cy.get('[data-cy="team-picker"]').should("not.exist");
    cy.get('[data-cy="schedule-game-row"][data-cy-game-id="1"]').should("exist");
    cy.get('[data-cy="schedule-game-row"][data-cy-game-id="9007"]').should("exist");
    // A non-NYM game (Yankees @ Red Sox, id 9004) should be filtered out.
    cy.get('[data-cy="schedule-game-row"][data-cy-game-id="9004"]').should("not.exist");
  });
});
