/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/scores", () => {
  beforeEach(() => {
    // Order matters: mockScoreboard before visit so the initial fetch is
    // intercepted; visitAsUser then writes the dl_user profile into the
    // target window inside onBeforeLoad so the boot script in app/layout.tsx
    // and the shell layout's onboarding gate both see a hydrated user before
    // first paint.
    cy.mockScoreboard();
    cy.visitAsUser("/scores");
    cy.wait("@scoreboard");
  });

  it("load /scores as a returning user → scoreboard renders without onboarding overlay flash", () => {
    cy.get('[data-cy="scores-screen"]').should("be.visible");
    // Onboarding step 1 has a distinctive "your name?" heading. Its absence
    // confirms the layout's `hydrated` gate is suppressing the overlay flash
    // for a returning user.
    cy.contains(/your name\?/i).should("not.exist");
    // At least one score card from the fixture should be on screen.
    cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    // Each card shows both teams' W-L as secondary text under the abbr
    // (fixture id=1 is NYM 22-17 @ PHI 20-19).
    cy.get('[data-cy="score-card"][data-cy-game-id="1"]')
      .find('[data-cy="team-record"]')
      .should("have.length", 2)
      .and(($els) => {
        const text = [...$els].map((el) => el.textContent?.trim()).join(" ");
        expect(text).to.include("22 - 17");
        expect(text).to.include("20 - 19");
      });
  });

  it("view scoreboard with followed teams in fixture → Following section lists those teams' games", () => {
    cy.get('[data-cy="following-section"]')
      .should("be.visible")
      .within(() => {
        cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
        // Either NYM or PHI should appear in this section's cards.
        cy.contains(/NYM|PHI/).should("exist");
      });
  });

  it("render games of mixed status → LIVE, FINAL, and SCHEDULED copy each appear on at least one card", () => {
    cy.get('[data-cy="score-card-status"]')
      .filter(':contains("LIVE")')
      .should("have.length.at.least", 1);
    cy.get('[data-cy="score-card-status"]')
      .filter(':contains("FINAL")')
      .should("have.length.at.least", 1);
    // Scheduled games show a clock-style time string ("10:15 PM" from fixture).
    cy.get('[data-cy="score-card-status"]')
      .filter(":contains(':')")
      .should("have.length.at.least", 1);
  });

  // Added by Cypress Author on 2026-07-07.
  it("view a completed game → card credits the winning and losing pitcher, not probables", () => {
    // Fixture id=2 (NYM @ ATL) is FINAL with decisions posted
    // (W: Spencer Strider / L: Kodai Senga). NYM is followed, so the card
    // renders in the Following section.
    cy.get('[data-cy="score-card"][data-cy-game-id="2"]').within(() => {
      cy.get('[data-cy="score-card-status"]').should("contain", "FINAL");
      // The W/L decisions strip replaces the probable-starters line.
      cy.get('[data-cy="score-card-decisions"]')
        .should("exist")
        .and(($el) => {
          const text = $el.text();
          expect(text).to.include("W: Spencer Strider");
          expect(text).to.include("L: Kodai Senga");
        });
      // Probables must not render on a final game.
      cy.get('[data-cy="score-card-probables"]').should("not.exist");
    });
  });

  it("click the MLB header toggle twice → games collapse, then re-expand", () => {
    cy.get('[data-cy="mlb-section"]').within(() => {
      cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    });
    cy.get('[data-cy="mlb-collapse-toggle"]').click();
    cy.get('[data-cy="mlb-section"]').within(() => {
      cy.get('[data-cy="score-card"]').should("not.exist");
    });
    cy.get('[data-cy="mlb-collapse-toggle"]').click();
    cy.get('[data-cy="mlb-section"]').within(() => {
      cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    });
  });

  it("click a score card → navigates to /game/[id] for that game", () => {
    // The live game in the fixture has id=1, which the API route short-circuits
    // to FIXTURE_LIVE_GAME — so the destination page is fully populated.
    cy.get('[data-cy="score-card"][data-cy-game-id="1"]').click();
    cy.location("pathname").should("eq", "/game/1");
  });
});
