/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/scores", () => {
  beforeEach(() => {
    // Order matters: mockScoreboard before visit so the initial fetch is
    // intercepted; visitAsUser then writes the dl_user profile into the
    // target window inside onBeforeLoad so the boot script in app/layout.tsx
    // and the shell layout's onboarding gate both see a hydrated user before
    // first paint.
    cy.mockScoreboard();
    cy.visitAsUser("/scores");
    cy.wait("@scoreboard");
  });

  it("load /scores as a returning user → scoreboard renders without onboarding overlay flash", () => {
    cy.get('[data-cy="scores-screen"]').should("be.visible");
    // Onboarding step 1 has a distinctive "your name?" heading. Its absence
    // confirms the layout's `hydrated` gate is suppressing the overlay flash
    // for a returning user.
    cy.contains(/your name\?/i).should("not.exist");
    // At least one score card from the fixture should be on screen.
    cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    // Each card shows both teams' W-L as secondary text under the abbr
    // (fixture id=1 is NYM 22-17 @ PHI 20-19).
    cy.get('[data-cy="score-card"][data-cy-game-id="1"]')
      .find('[data-cy="team-record"]')
      .should("have.length", 2)
      .and(($els) => {
        const text = [...$els].map((el) => el.textContent?.trim()).join(" ");
        expect(text).to.include("22 - 17");
        expect(text).to.include("20 - 19");
      });
  });

  it("view scoreboard with followed teams in fixture → Following section lists those teams' games", () => {
    cy.get('[data-cy="following-section"]')
      .should("be.visible")
      .within(() => {
        cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
        // Either NYM or PHI should appear in this section's cards.
        cy.contains(/NYM|PHI/).should("exist");
      });
  });

  it("render games of mixed status → LIVE, FINAL, SCHEDULED, and POSTPONED copy each appear on at least one card", () => {
    cy.get('[data-cy="score-card-status"]')
      .filter(':contains("LIVE")')
      .should("have.length.at.least", 1);
    cy.get('[data-cy="score-card-status"]')
      .filter(':contains("FINAL")')
      .should("have.length.at.least", 1);
    // Scheduled games show a clock-style time string ("10:15 PM" from fixture).
    cy.get('[data-cy="score-card-status"]')
      .filter(":contains(':')")
      .should("have.length.at.least", 1);
    // Postponed games (fixture id=5) surface a "Postponed" label.
    cy.get('[data-cy="score-card-status"]')
      .filter(':contains("Postponed")')
      .should("have.length.at.least", 1);
  });

  // Added by Cypress Author on 2026-07-07.
  it("view a postponed game → card reads 'Postponed', never 'FINAL'", () => {
    // Fixture id=5 (CHC @ STL) is POSTPONED. A rained-out game must not be
    // miscategorized as a completed (FINAL) game.
    cy.get('[data-cy="score-card"][data-cy-game-id="5"]')
      .find('[data-cy="score-card-status"]')
      .should("contain", "Postponed")
      .and("not.contain", "FINAL");
  });

  // Added by Cypress Author on 2026-07-07.
  it("view a completed game → card credits the winning and losing pitcher, not probables", () => {
    // Fixture id=2 (NYM @ ATL) is FINAL with decisions posted
    // (W: Spencer Strider / L: Kodai Senga). NYM is followed, so the card
    // renders in the Following section.
    cy.get('[data-cy="score-card"][data-cy-game-id="2"]').within(() => {
      cy.get('[data-cy="score-card-status"]').should("contain", "FINAL");
      // The W/L decisions strip replaces the probable-starters line.
      cy.get('[data-cy="score-card-decisions"]')
        .should("exist")
        .and(($el) => {
          const text = $el.text();
          expect(text).to.include("W: Spencer Strider");
          expect(text).to.include("L: Kodai Senga");
        });
      // Probables must not render on a final game.
      cy.get('[data-cy="score-card-probables"]').should("not.exist");
    });
  });

  it("click the MLB header toggle twice → games collapse, then re-expand", () => {
    cy.get('[data-cy="mlb-section"]').within(() => {
      cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    });
    cy.get('[data-cy="mlb-collapse-toggle"]').click();
    cy.get('[data-cy="mlb-section"]').within(() => {
      cy.get('[data-cy="score-card"]').should("not.exist");
    });
    cy.get('[data-cy="mlb-collapse-toggle"]').click();
    cy.get('[data-cy="mlb-section"]').within(() => {
      cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    });
  });

  // Added by Cypress Author on 2026-07-31.
  it("background the tab, then bring it back → scoreboard refetches on return, not while hidden", () => {
    // `document.visibilityState` is a read-only accessor inherited from
    // Document.prototype, so override it on the AUT document before dispatching
    // the event the browser would normally fire itself. `configurable: true`
    // keeps it replaceable for the second call. No teardown needed: the
    // beforeEach `visitAsUser` reloads the page for every test.
    const setVisibility = (win: Cypress.AUTWindow, state: DocumentVisibilityState) => {
      Object.defineProperty(win.document, "visibilityState", {
        value: state,
        configurable: true,
      });
      win.document.dispatchEvent(new win.Event("visibilitychange"));
    };

    // Baseline: only the initial mount fetch has landed. The 10s poll can't
    // fire within this test's runtime and the notification poll is inert (the
    // `user` fixture has notifications disabled), so any further call is
    // attributable to the visibility listener in lib/mlb/client.ts.
    cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    cy.get("@scoreboard.all").should("have.length", 1);

    // Hidden: the handler checks visibilityState and bails, so no request.
    cy.window().then((win) => setVisibility(win, "hidden"));
    cy.get("@scoreboard.all").should("have.length", 1);

    // Foregrounded: refetch immediately rather than waiting out the throttled
    // poll interval.
    cy.window().then((win) => setVisibility(win, "visible"));
    cy.wait("@scoreboard");
    cy.get("@scoreboard.all").should("have.length", 2);

    // The refetch swaps data in place — cards stay rendered, and the screen
    // must not fall back to the loading placeholder mid-refresh. Polls bump the
    // fetch generation inside a transition, so React keeps the resolved board
    // mounted rather than re-suspending the boundary into its skeleton.
    cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    cy.get('[data-cy="loading"]').should("not.exist");
    cy.get('[data-cy="scores-skeleton"]').should("not.exist");
  });

  // Added by Cypress Author on 2026-08-28.
  it("select a different date in the strip → skeleton shows while it loads, then that date's board renders", () => {
    // Each date gets its own keyed <Suspense> boundary, so a date change is a
    // first load: it suspends to the skeleton rather than swapping in place.
    // The strip is built from the real `new Date()` at runtime, so read the
    // target date out of the DOM instead of hardcoding an ISO string.
    cy.get('[data-cy="date-pill"][data-cy-selected="true"]')
      .next('[data-cy="date-pill"]')
      .invoke("attr", "data-cy-date")
      .then((iso) => {
        // Registered after the beforeEach catch-all — Cypress matches handlers
        // newest-first, so this more specific one wins for the target date. The
        // delay makes the fallback observable instead of a single-frame flash.
        cy.intercept("GET", `/api/mlb/scoreboard?date=${iso}`, {
          fixture: "scoreboard-future",
          delay: 400,
        }).as("scoreboardFuture");

        cy.get(`[data-cy="date-pill"][data-cy-date="${iso}"]`).click();

        // Suspended: the board is replaced by the skeleton, but the strip lives
        // outside the boundary and stays on screen (and clickable) throughout.
        cy.get('[data-cy="scores-skeleton"]').should("be.visible");
        cy.get('[data-cy="loading"]').should("be.visible");
        cy.get('[data-cy="date-pill"]').should("have.length.at.least", 2);

        cy.wait("@scoreboardFuture");

        // Resolved: the fallback is gone and the *new* date's games are on
        // screen — the future fixture is two scheduled games (HOU@SEA, TOR@BAL),
        // none of which appear in scoreboard-today.
        cy.get('[data-cy="scores-skeleton"]').should("not.exist");
        cy.get('[data-cy="scores-screen"]').should("be.visible");
        cy.get('[data-cy="score-card"]').should("have.length", 2);
        cy.get('[data-cy="score-card"][data-cy-game-id="101"]').should("exist");
        cy.get('[data-cy="score-card"][data-cy-game-id="102"]').should("exist");
        // Today's live game must not survive the date change.
        cy.get('[data-cy="score-card"][data-cy-game-id="1"]').should("not.exist");
      });
  });

  it("click a score card → navigates to /game/[id] for that game", () => {
    // The live game in the fixture has id=1, which the API route short-circuits
    // to FIXTURE_LIVE_GAME — so the destination page is fully populated.
    cy.get('[data-cy="score-card"][data-cy-game-id="1"]').click();
    cy.location("pathname").should("eq", "/game/1");
  });

  // Added by Cypress Author on 2026-08-28.
  it("view a board where every game has finished → the poll never fires again", () => {
    // Deliberately NOT using cy.clock here. `pollWhile` tears the interval down
    // from a promise callback, which lands in a different microtask than the
    // render that commits the data — so a fake clock ticked right after the DOM
    // assertions below can catch the interval in the instant before it is
    // cleared, fire it, and produce a request storm that has nothing to do with
    // the behaviour under test. Spanning one real poll interval is slower but
    // races with nothing. The wait below is the subject of the assertion, not an
    // attempt to paper over timing.

    // Derive an all-finished slate from the existing fixture rather than
    // maintaining a near-duplicate of it. POSTPONED is left alone: it counts as
    // terminal too, so the board should still go quiet.
    cy.fixture("scoreboard-today").then((board) => {
      const finished = {
        ...board,
        games: board.games.map((g: { status: string }) => ({
          ...g,
          status: g.status === "POSTPONED" ? "POSTPONED" : "FINAL",
        })),
      };
      cy.intercept("GET", "/api/mlb/scoreboard*", { body: finished }).as("finishedBoard");
    });

    cy.visitAsUser("/scores");
    cy.wait("@finishedBoard");
    cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    cy.get('[data-cy="score-card-status"]').filter(':contains("LIVE")').should("not.exist");

    // Baseline immediately before the wait: navigating away from the beforeEach
    // page lets that instance fire a parting request which this intercept also
    // matches. Measuring the delta isolates the only thing under test — whether
    // the poll interval is still alive.
    let baseline = 0;
    cy.get("@finishedBoard.all").then((calls) => {
      baseline = (calls as unknown as unknown[]).length;
    });

    // Sit out a full poll interval (10s) plus margin. A live board would have
    // issued at least one request in this window — the positive-control test
    // below proves that — so a flat count here means the interval really was
    // retired.
    cy.wait(13_000);
    cy.get("@finishedBoard.all").should((calls) => {
      expect(calls, "finished board issues no polls").to.have.length(baseline);
    });
  });

  // Added by Cypress Author on 2026-08-28.
  it("view a board with a game still in progress → poll keeps firing on the interval", () => {
    // Positive control for the test above. The default fixture has LIVE and
    // SCHEDULED games, so the board must keep polling.
    //
    // A fake interval clock is safe here, unlike in the negative test: `pollable`
    // stays true for this fixture, so there is no teardown to race against and
    // ticking cannot catch the interval mid-transition.
    cy.clock(null, ["setInterval", "clearInterval"]);
    cy.mockScoreboard();
    cy.visitAsUser("/scores");
    cy.wait("@scoreboard");
    cy.get('[data-cy="score-card-status"]')
      .filter(':contains("LIVE")')
      .should("have.length.at.least", 1);

    let baseline = 0;
    cy.get("@scoreboard.all").then((calls) => {
      baseline = (calls as unknown as unknown[]).length;
    });

    cy.tick(30_000);
    // `refresh()` runs inside a transition, so React schedules the render — and
    // the fetch inside it — after the tick returns. Give it a beat to land.
    cy.wait(750);
    cy.get("@scoreboard.all").should((calls) => {
      const delta = (calls as unknown as unknown[]).length - baseline;
      expect(delta, "live board keeps polling").to.be.greaterThan(0);
      // Upper bound is the real point of this assertion. A `refresh` whose state
      // updater is impure makes every suspended retry mint another request, and
      // that loop reads as "polling works" to a lower-bound-only check while it
      // hammers the endpoint hundreds of times. Three fake intervals must produce
      // a handful of requests, not a flood.
      expect(delta, "polling is paced, not a retry storm").to.be.at.most(8);
    });
  });
});
