/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/scores", () => {
  beforeEach(() => {
    // Order matters: mockScoreboard before visit so the initial fetch is
    // intercepted; visitAsUser then writes the dl_user profile into the
    // target window inside onBeforeLoad so the boot script in app/layout.tsx
    // and the shell layout's onboarding gate both see a hydrated user before
    // first paint.
    cy.mockScoreboard();
    cy.visitAsUser("/scores");
    cy.wait("@scoreboard");
  });

  it("load /scores as a returning user → scoreboard renders without onboarding overlay flash", () => {
    cy.get('[data-cy="scores-screen"]').should("be.visible");
    // Onboarding step 1 has a distinctive "your name?" heading. Its absence
    // confirms the layout's `hydrated` gate is suppressing the overlay flash
    // for a returning user.
    cy.contains(/your name\?/i).should("not.exist");
    // At least one score card from the fixture should be on screen.
    cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    // Each card shows both teams' W-L as secondary text under the abbr
    // (fixture id=1 is NYM 22-17 @ PHI 20-19).
    cy.get('[data-cy="score-card"][data-cy-game-id="1"]')
      .find('[data-cy="team-record"]')
      .should("have.length", 2)
      .and(($els) => {
        const text = [...$els].map((el) => el.textContent?.trim()).join(" ");
        expect(text).to.include("22 - 17");
        expect(text).to.include("20 - 19");
      });
  });

  it("view scoreboard with followed teams in fixture → Following section lists those teams' games", () => {
    cy.get('[data-cy="following-section"]')
      .should("be.visible")
      .within(() => {
        cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
        // Either NYM or PHI should appear in this section's cards.
        cy.contains(/NYM|PHI/).should("exist");
      });
  });

  it("render games of mixed status → LIVE, FINAL, SCHEDULED, and POSTPONED copy each appear on at least one card", () => {
    cy.get('[data-cy="score-card-status"]')
      .filter(':contains("LIVE")')
      .should("have.length.at.least", 1);
    cy.get('[data-cy="score-card-status"]')
      .filter(':contains("FINAL")')
      .should("have.length.at.least", 1);
    // Scheduled games show a clock-style time string ("10:15 PM" from fixture).
    cy.get('[data-cy="score-card-status"]')
      .filter(":contains(':')")
      .should("have.length.at.least", 1);
    // Postponed games (fixture id=5) surface a "Postponed" label.
    cy.get('[data-cy="score-card-status"]')
      .filter(':contains("Postponed")')
      .should("have.length.at.least", 1);
  });

  // Added by Cypress Author on 2026-07-07.
  it("view a postponed game → card reads 'Postponed', never 'FINAL'", () => {
    // Fixture id=5 (CHC @ STL) is POSTPONED. A rained-out game must not be
    // miscategorized as a completed (FINAL) game.
    cy.get('[data-cy="score-card"][data-cy-game-id="5"]')
      .find('[data-cy="score-card-status"]')
      .should("contain", "Postponed")
      .and("not.contain", "FINAL");
  });

  // Added by Cypress Author on 2026-07-07.
  it("view a completed game → card credits the winning and losing pitcher, not probables", () => {
    // Fixture id=2 (NYM @ ATL) is FINAL with decisions posted
    // (W: Spencer Strider / L: Kodai Senga). NYM is followed, so the card
    // renders in the Following section.
    cy.get('[data-cy="score-card"][data-cy-game-id="2"]').within(() => {
      cy.get('[data-cy="score-card-status"]').should("contain", "FINAL");
      // The W/L decisions strip replaces the probable-starters line.
      cy.get('[data-cy="score-card-decisions"]')
        .should("exist")
        .and(($el) => {
          const text = $el.text();
          expect(text).to.include("W: Spencer Strider");
          expect(text).to.include("L: Kodai Senga");
        });
      // Probables must not render on a final game.
      cy.get('[data-cy="score-card-probables"]').should("not.exist");
    });
  });

  it("click the MLB header toggle twice → games collapse, then re-expand", () => {
    cy.get('[data-cy="mlb-section"]').within(() => {
      cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    });
    cy.get('[data-cy="mlb-collapse-toggle"]').click();
    cy.get('[data-cy="mlb-section"]').within(() => {
      cy.get('[data-cy="score-card"]').should("not.exist");
    });
    cy.get('[data-cy="mlb-collapse-toggle"]').click();
    cy.get('[data-cy="mlb-section"]').within(() => {
      cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    });
  });

  // Added by Cypress Author on 2026-07-31.
  it("background the tab, then bring it back → scoreboard refetches on return, not while hidden", () => {
    // `document.visibilityState` is a read-only accessor inherited from
    // Document.prototype, so override it on the AUT document before dispatching
    // the event the browser would normally fire itself. `configurable: true`
    // keeps it replaceable for the second call. No teardown needed: the
    // beforeEach `visitAsUser` reloads the page for every test.
    const setVisibility = (win: Cypress.AUTWindow, state: DocumentVisibilityState) => {
      Object.defineProperty(win.document, "visibilityState", {
        value: state,
        configurable: true,
      });
      win.document.dispatchEvent(new win.Event("visibilitychange"));
    };

    // Baseline: only the initial mount fetch has landed. The 20s poll can't
    // fire within this test's runtime and the notification poll is inert (the
    // `user` fixture has notifications disabled), so any further call is
    // attributable to the visibility listener in lib/mlb/client.ts.
    cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    cy.get("@scoreboard.all").should("have.length", 1);

    // Hidden: the handler checks visibilityState and bails, so no request.
    cy.window().then((win) => setVisibility(win, "hidden"));
    cy.get("@scoreboard.all").should("have.length", 1);

    // Foregrounded: refetch immediately rather than waiting out the throttled
    // poll interval.
    cy.window().then((win) => setVisibility(win, "visible"));
    cy.wait("@scoreboard");
    cy.get("@scoreboard.all").should("have.length", 2);

    // The refetch swaps data in place — cards stay rendered, and the screen
    // must not fall back to the loading placeholder mid-refresh.
    cy.get('[data-cy="score-card"]').should("have.length.at.least", 1);
    cy.get('[data-cy="loading"]').should("not.exist");
  });

  it("click a score card → navigates to /game/[id] for that game", () => {
    // The live game in the fixture has id=1, which the API route short-circuits
    // to FIXTURE_LIVE_GAME — so the destination page is fully populated.
    cy.get('[data-cy="score-card"][data-cy-game-id="1"]').click();
    cy.location("pathname").should("eq", "/game/1");
  });
});
