/// <reference types="cypress" />

// Generated by Cypress Author on 2026-06-17.

// SearchScreen queries Supabase directly via `supabase.rpc("search_entities")`.
// Under E2E_MODE the browser client targets the placeholder Supabase host, so
// the call is a *cross-origin* POST to `/rest/v1/rpc/search_entities`. We stub
// both the CORS preflight (OPTIONS) and the POST, attaching permissive CORS
// headers so the browser lets the app read the stubbed response.
const RPC = "**/rest/v1/rpc/search_entities";
const CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-headers": "*",
  "access-control-allow-methods": "*",
};

/** Stub the search RPC. Pass `{ fixture }` or `{ body }` for the POST payload. */
function stubSearch(response: { fixture: string } | { body: unknown }) {
  cy.intercept("OPTIONS", RPC, { statusCode: 204, headers: CORS });
  cy.intercept("POST", RPC, { statusCode: 200, headers: CORS, ...response }).as("search");
}

describe("/search", () => {
  it("load /search → search input is focused on load and the hint is shown", () => {
    // No query yet, so the RPC never fires — just assert the empty state.
    stubSearch({ body: [] });
    cy.visitAsUser("/search");

    cy.get('[data-cy="search-screen"]').should("be.visible");
    // SearchScreen autofocuses its input on mount.
    cy.focused().should("have.attr", "data-cy", "search-input");
    cy.get('[data-cy="search-hint"]').should("be.visible");
    cy.get('[data-cy="search-results"]').should("not.exist");
  });

  it("type a query → debounced RPC fires and player + team results render", () => {
    stubSearch({ fixture: "search-entities.json" });
    cy.visitAsUser("/search");

    cy.get('[data-cy="search-input"]').type("yankee");
    cy.wait("@search");

    cy.get('[data-cy="search-result"]').should("have.length", 3);
    cy.contains('[data-cy="search-result"]', "New York Yankees").should("be.visible");
    cy.contains('[data-cy="search-result"]', "Aaron Judge").should("be.visible");
    cy.get('[data-cy="search-hint"]').should("not.exist");
  });

  it("click a player result → navigates to /player/[id]", () => {
    stubSearch({ fixture: "search-entities.json" });
    cy.visitAsUser("/search");

    cy.get('[data-cy="search-input"]').type("judge");
    cy.wait("@search");

    cy.get('[data-cy="search-result"][data-cy-entity-type="player"][data-cy-uid="592450"]').click();
    cy.location("pathname").should("eq", "/player/592450");
  });

  it("click the Diamondbacks team result → navigates to /team/ARI (index abbr AZ normalized)", () => {
    stubSearch({ fixture: "search-entities.json" });
    cy.visitAsUser("/search");

    cy.get('[data-cy="search-input"]').type("arizona");
    cy.wait("@search");

    // The search index stores Arizona as "AZ"; the screen resolves the app's
    // canonical "ARI" from team_id before routing.
    cy.get('[data-cy="search-result"][data-cy-entity-type="team"][data-cy-uid="109"]').click();
    cy.location("pathname").should("eq", "/team/ARI");
  });

  it("visit /search?q=yankee → input is pre-filled and a search runs on load", () => {
    stubSearch({ fixture: "search-entities.json" });
    cy.visitAsUser("/search?q=yankee");

    cy.get('[data-cy="search-input"]').should("have.value", "yankee");
    cy.wait("@search");
    cy.get('[data-cy="search-result"]').should("have.length", 3);
  });

  it("click clear → empties the input, refocuses it, and restores the hint", () => {
    stubSearch({ fixture: "search-entities.json" });
    cy.visitAsUser("/search");

    cy.get('[data-cy="search-input"]').type("yankee");
    cy.wait("@search");
    cy.get('[data-cy="search-result"]').should("have.length", 3);

    cy.get('[data-cy="search-clear"]').click();
    cy.get('[data-cy="search-input"]').should("have.value", "");
    cy.focused().should("have.attr", "data-cy", "search-input");
    // The cleared query debounces back to blank, which restores the hint.
    cy.get('[data-cy="search-hint"]').should("be.visible");
    cy.get('[data-cy="search-results"]').should("not.exist");
  });

  it("query with no matches → empty-state message is shown", () => {
    stubSearch({ body: [] });
    cy.visitAsUser("/search");

    cy.get('[data-cy="search-input"]').type("zzzzzzzz");
    cy.wait("@search");

    cy.get('[data-cy="search-empty"]').should("be.visible");
    cy.get('[data-cy="search-result"]').should("not.exist");
  });

  it("click the Search nav tab from /scores → routes to /search with the input focused", () => {
    cy.mockScoreboard();
    stubSearch({ body: [] });
    cy.visitAsUser("/scores");

    // On the mobile viewport the bottom TabBar is the visible nav; the desktop
    // TopBar carries the same data-cy but is display:none, so filter to visible.
    cy.get('[data-cy="nav-tab"][data-cy-tab="search"]').filter(":visible").click();

    cy.location("pathname").should("eq", "/search");
    cy.focused().should("have.attr", "data-cy", "search-input");
  });
});
