/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-16.

describe("/settings", () => {
  it("load /settings as authenticated user → Account card with sign-out button renders", () => {
    cy.visitAsAuthenticatedUser("/settings");
    // The Account card is gated on `isAuthed` — guests don't see it. Its
    // presence is the structural signal that the auth-store seeding via
    // `dl_e2e_authenticated` was picked up correctly.
    cy.get('[data-cy="account-card"]').should("be.visible");
    cy.get('[data-cy="sign-out"]').should("be.visible").and("contain", "Sign out");
    // Email comes from the synthetic E2E identity in lib/storage.ts.
    cy.get('[data-cy="account-email"]').should("contain", "e2e@cypress.test");
  });

  it("load /settings as guest → Account card is hidden, reset-onboarding fallback shown instead", () => {
    cy.visitAsUser("/settings");
    cy.get('[data-cy="account-card"]').should("not.exist");
    cy.get('[data-cy="sign-out"]').should("not.exist");
    // The guest path replaces the sign-out button with the reset-onboarding
    // affordance — easiest negative-space proof that we're on the guest
    // branch of SettingsScreen.
    cy.contains(/reset onboarding/i).should("be.visible");
  });

  it("click sign-out → server-action redirects to /login", () => {
    cy.visitAsAuthenticatedUser("/settings");
    cy.get('[data-cy="sign-out"]').click();
    // signOut() under E2E_MODE skips the Supabase call but still issues a
    // server-side redirect("/login") — that 303 is what Cypress is
    // asserting on here, and what stays stable on iOS Safari (the
    // pre-refactor router.push + router.refresh combo would race and
    // sometimes blank the destination).
    cy.location("pathname").should("eq", "/login");
  });
});
