/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/standings", () => {
  beforeEach(() => {
    // mockGet before visit so the initial standings fetch is intercepted;
    // cy.visitAsUser seeds the dl_user profile so the onboarding overlay
    // doesn't gate the page.
    cy.intercept("GET", "/api/mlb/standings*", { fixture: "standings.json" }).as("standings");
    cy.visitAsUser("/standings");
    cy.wait("@standings");
  });

  it("load /standings → AL divisions render with team rows by default", () => {
    cy.get('[data-cy="standings-screen"]').should("be.visible");
    cy.contains("AL East").should("be.visible");
    cy.contains("AL Central").should("be.visible");
    cy.contains("AL West").should("be.visible");
    // 5 teams per AL division × 3 divisions = 15 rows
    cy.get('[data-cy="standings-row"]').should("have.length", 15);
    // First team in AL East (NYY, the division leader in our fixture) is rendered
    cy.get('[data-cy="standings-row"][data-cy-team="NYY"]').should("exist");
  });

  it("click NL toggle → NL divisions render in place", () => {
    cy.get('[data-cy="league-toggle"][data-cy-league="NL"]').click();
    cy.contains("NL East").should("be.visible");
    cy.contains("NL Central").should("be.visible");
    cy.contains("NL West").should("be.visible");
    cy.get('[data-cy="standings-row"]').should("have.length", 15);
    cy.get('[data-cy="standings-row"][data-cy-team="PHI"]').should("exist");
    // AL divisions are no longer shown
    cy.contains("AL East").should("not.exist");
  });

  it("click a team row → navigates to /team/[abbr]", () => {
    cy.get('[data-cy="league-toggle"][data-cy-league="NL"]').click();
    cy.get('[data-cy="standings-row"][data-cy-team="NYM"]').click();
    cy.location("pathname").should("eq", "/team/NYM");
  });

  // Generated by Cypress Author on 2026-07-30.

  it("click Playoffs toggle → both leagues stack, each split by division", () => {
    cy.get('[data-cy="league-toggle"][data-cy-league="playoffs"]').click();

    // One table per league, AL above NL, replacing the division cards.
    cy.get('[data-cy="playoff-table"]').should("have.length", 2);
    cy.get('[data-cy="playoff-table"]').eq(0).should("have.attr", "data-cy-league", "AL");
    cy.get('[data-cy="playoff-table"]').eq(1).should("have.attr", "data-cy-league", "NL");
    cy.contains("American League").should("be.visible");
    // Below the fold in the 402×874 viewport — assert presence, not visibility.
    cy.contains("National League").should("exist");

    // Three division groups per league, in East → Central → West order.
    cy.get('[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-division"]')
      .then(($groups) => {
        const names = $groups.toArray().map((el) => el.getAttribute("data-cy-division"));
        expect(names).to.deep.equal(["AL East", "AL Central", "AL West"]);
      });
    cy.get('[data-cy="playoff-table"][data-cy-league="NL"] [data-cy="playoff-division"]')
      .then(($groups) => {
        const names = $groups.toArray().map((el) => el.getAttribute("data-cy-division"));
        expect(names).to.deep.equal(["NL East", "NL Central", "NL West"]);
      });

    // Every team in the league appears once: 5 teams × 3 divisions.
    cy.get('[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"]')
      .should("have.length", 15);
    cy.get('[data-cy="playoff-table"][data-cy-league="NL"] [data-cy="playoff-row"]')
      .should("have.length", 15);

    // Rows sit under their own division, ordered by division finish, and carry
    // the league-wide seed — so seeds are interleaved, not sequential.
    cy.get('[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"]')
      .then(($rows) => {
        const rows = $rows.toArray().map((el) => ({
          team: el.getAttribute("data-cy-team"),
          seed: el.getAttribute("data-cy-seed"),
        }));
        // AL East leads off: NYY (seed 1) then BOS, the league's 4th seed.
        expect(rows.slice(0, 5).map((r) => r.team)).to.deep.equal([
          "NYY", "BOS", "TOR", "TB", "BAL",
        ]);
        expect(rows.slice(0, 2).map((r) => r.seed)).to.deep.equal(["1", "4"]);
        // Each seed 1–15 is handed out exactly once across the league.
        expect(rows.map((r) => r.seed).sort((a, b) => Number(a) - Number(b)))
          .to.deep.equal(Array.from({ length: 15 }, (_, i) => String(i + 1)));
      });
    // LAD is the NL's top seed but sits in the NL West group, not at the top.
    cy.get('[data-cy="playoff-table"][data-cy-league="NL"] [data-cy="playoff-row"][data-cy-team="LAD"]')
      .should("have.attr", "data-cy-seed", "1");

    // The toggle is reflected in the URL so the view is linkable.
    cy.location("search").should("contain", "league=playoffs");
  });

  it("view playoff standings → leaders, wild cards, and teams out are distinguished", () => {
    cy.get('[data-cy="league-toggle"][data-cy-league="playoffs"]').click();

    // 3 division winners + 3 wild cards make the field in each league; the
    // remaining 9 are out. Status drives each row's background color.
    for (const league of ["AL", "NL"]) {
      cy.get(
        `[data-cy="playoff-table"][data-cy-league="${league}"] [data-cy="playoff-row"][data-cy-status="division-leader"]`,
      ).should("have.length", 3);
      cy.get(
        `[data-cy="playoff-table"][data-cy-league="${league}"] [data-cy="playoff-row"][data-cy-status="wild-card"]`,
      ).should("have.length", 3);
      cy.get(
        `[data-cy="playoff-table"][data-cy-league="${league}"] [data-cy="playoff-row"][data-cy-status="out"]`,
      ).should("have.length", 9);
    }

    // A division leader and a wild card do not share a background color.
    cy.get('[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"][data-cy-team="NYY"]')
      .invoke("css", "background-color")
      .then((leaderBg) => {
        cy.get('[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"][data-cy-team="BOS"]')
          .invoke("css", "background-color")
          .should("not.eq", leaderBg);
      });

    // Each division's leader is the first row in its group.
    cy.get('[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"][data-cy-status="division-leader"]')
      .then(($leaders) => {
        const teams = $leaders.toArray().map((el) => el.getAttribute("data-cy-team"));
        expect(teams).to.deep.equal(["NYY", "DET", "HOU"]);
      });

    // GB is signed against the cut line: teams in the field read positive,
    // teams outside read negative. AL fixture: MIN (21-17) is the last team in,
    // TOR (20-18) the first out — one game apart either side of the line.
    // Kept as separate chains: `have.attr` changes the subject to the
    // attribute value, so a `.find()` chained off it would have no element.
    cy.get('[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"][data-cy-team="MIN"]')
      .should("have.attr", "data-cy-seed", "6");
    cy.get(
      '[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"][data-cy-team="MIN"] [data-cy="playoff-gb"]',
    ).should("have.text", "+1.0");
    cy.get('[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"][data-cy-team="TOR"]')
      .should("have.attr", "data-cy-seed", "7");
    cy.get(
      '[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"][data-cy-team="TOR"] [data-cy="playoff-gb"]',
    ).should("have.text", "-1.0");
    // Top seed sits furthest clear of the line.
    cy.get(
      '[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"][data-cy-team="NYY"] [data-cy="playoff-gb"]',
    ).should("have.text", "+4.0");
    cy.get(
      '[data-cy="playoff-table"][data-cy-league="NL"] [data-cy="playoff-row"][data-cy-team="LAD"] [data-cy="playoff-gb"]',
    ).should("have.text", "+5.0");

    // Record and win percentage ride along on each row.
    cy.get('[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"][data-cy-team="NYY"]')
      .should("contain.text", "24")
      .and("contain.text", "14")
      .and("contain.text", ".632");

    // The legend keys the two berth colors.
    cy.get('[data-cy="playoff-legend"]')
      .should("contain.text", "Division leader")
      .and("contain.text", "Wild card");
  });

  it("click a playoff row → navigates to /team/[abbr]", () => {
    cy.get('[data-cy="league-toggle"][data-cy-league="playoffs"]').click();
    cy.get('[data-cy="playoff-table"][data-cy-league="AL"] [data-cy="playoff-row"][data-cy-team="NYY"]')
      .click();
    cy.location("pathname").should("eq", "/team/NYY");
  });
});
