/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-12.

describe("/standings", () => {
  beforeEach(() => {
    // mockGet before visit so the initial standings fetch is intercepted;
    // cy.visitAsUser seeds the dl_user profile so the onboarding overlay
    // doesn't gate the page.
    cy.intercept("GET", "/api/mlb/standings*", { fixture: "standings.json" }).as("standings");
    cy.visitAsUser("/standings");
    cy.wait("@standings");
  });

  it("load /standings → AL divisions render with team rows by default", () => {
    cy.get('[data-cy="standings-screen"]').should("be.visible");
    cy.contains("AL East").should("be.visible");
    cy.contains("AL Central").should("be.visible");
    cy.contains("AL West").should("be.visible");
    // 5 teams per AL division × 3 divisions = 15 rows
    cy.get('[data-cy="standings-row"]').should("have.length", 15);
    // First team in AL East (NYY, the division leader in our fixture) is rendered
    cy.get('[data-cy="standings-row"][data-cy-team="NYY"]').should("exist");
  });

  it("click NL toggle → NL divisions render in place", () => {
    cy.get('[data-cy="league-toggle"][data-cy-league="NL"]').click();
    cy.contains("NL East").should("be.visible");
    cy.contains("NL Central").should("be.visible");
    cy.contains("NL West").should("be.visible");
    cy.get('[data-cy="standings-row"]').should("have.length", 15);
    cy.get('[data-cy="standings-row"][data-cy-team="PHI"]').should("exist");
    // AL divisions are no longer shown
    cy.contains("AL East").should("not.exist");
  });

  it("click a team row → navigates to /team/[abbr]", () => {
    cy.get('[data-cy="league-toggle"][data-cy-league="NL"]').click();
    cy.get('[data-cy="standings-row"][data-cy-team="NYM"]').click();
    cy.location("pathname").should("eq", "/team/NYM");
  });
});
