/// <reference types="cypress" />

// Generated by Cypress Author on 2026-05-13.

describe("/team/[abbr]", () => {
  beforeEach(() => {
    // The three tab routes are intercepted before visit so first paint is hermetic.
    // Order: specific (/season, /personnel) before bare /team so the wildcard
    // doesn't shadow them. Cypress matches in registration order.
    cy.intercept("GET", "/api/mlb/team/NYM/season*", { fixture: "team-season.json" }).as("season");
    cy.intercept("GET", "/api/mlb/team/NYM/personnel*", { fixture: "team-personnel.json" }).as("personnel");
    cy.intercept("GET", "/api/mlb/team/NYM*", { fixture: "team-detail.json" }).as("roster");
    cy.visitAsUser("/team/NYM");
    cy.wait("@season");
  });

  it("load /team/NYM → Season tab is the default and renders record, last-5, stats", () => {
    cy.get('[data-cy="team-detail"]').should("be.visible");
    // The Season tab is active by default; assert via the active border class on its sub-tab.
    cy.get('[data-cy="sub-tab"][data-cy-tab="season"]').should("have.class", "border-accent");
    cy.get('[data-cy="season-tab"]').should("be.visible");
    // Record card: fixture has 22-17.
    cy.get('[data-cy="record-card"] [data-cy="record-wins"]').should("contain", "22");
    cy.get('[data-cy="record-card"] [data-cy="record-losses"]').should("contain", "17");
    // Last-5 games render as table rows, each linkable to /game/[id].
    cy.get('[data-cy="last-game-row"]').should("have.length", 5);
  });

  it("click Roster sub-tab → roster groups render, injured players hidden", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="roster"]').click();
    cy.wait("@roster");
    cy.get('[data-cy="roster-tab"]').should("be.visible");
    // Fixture has 11 active + 3 injured = 11 rows in roster.
    cy.get('[data-cy="roster-row"]').should("have.length", 11);
    // Position-group headers render.
    cy.contains("Pitchers").should("exist");
    cy.contains("Catchers").should("exist");
    cy.contains("Infielders").should("exist");
    cy.contains("Outfielders").should("exist");
  });

  it("click Injuries sub-tab → injured-only rows render with status codes and notes", () => {
    // Roster intercept's count is incidental; what matters is that the roster URL
    // resolves once and feeds both Roster and Injuries tabs via the in-memory cache.
    cy.get('[data-cy="sub-tab"][data-cy-tab="injuries"]').click();
    cy.get('[data-cy="injuries-tab"]').should("be.visible");
    cy.get('[data-cy="injury-row"]').should("have.length", 3);
    // Specific injury codes from the fixture.
    cy.contains("IL60").should("exist");
    cy.contains("IL15").should("exist");
    cy.contains("IL10").should("exist");
    // When `notes` is populated, it surfaces as the row's detail text. When
    // absent, the status description fills in (Tyrone Taylor has no notes).
    cy.contains("Right oblique strain").should("exist");
    cy.contains("Right shoulder soreness").should("exist");
    cy.contains("10-Day Injured List").should("exist");
  });

  it("click Personnel sub-tab → coaches + front-office tables render", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="personnel"]').click();
    cy.wait("@personnel");
    cy.get('[data-cy="personnel-tab"]').should("be.visible");
    cy.get('[data-cy="coaches-table"]').should("be.visible").within(() => {
      cy.get('[data-cy="personnel-row"]').should("have.length", 6);
      cy.contains("Carlos Mendoza").should("exist");
    });
    cy.get('[data-cy="front-office-table"]').should("be.visible").within(() => {
      cy.get('[data-cy="personnel-row"]').should("have.length", 4);
      cy.contains("Steve Cohen").should("exist");
    });
  });

  it("empty front office → Personnel tab hides that section silently", () => {
    // Re-load with the empty-FO fixture in place.
    cy.intercept("GET", "/api/mlb/team/NYM/personnel*", { fixture: "team-personnel-no-fo.json" })
      .as("personnelEmptyFo");
    // Force-refresh by re-visiting; the in-memory client cache survives nav, so we
    // need a fresh page load to clear it for this assertion.
    cy.visitAsUser("/team/NYM");
    cy.get('[data-cy="sub-tab"][data-cy-tab="personnel"]').click();
    cy.wait("@personnelEmptyFo");
    cy.get('[data-cy="coaches-table"]').should("be.visible");
    cy.get('[data-cy="front-office-table"]').should("not.exist");
  });

  it("click a roster row → navigates to /player/[id]", () => {
    cy.get('[data-cy="sub-tab"][data-cy-tab="roster"]').click();
    // Francisco Lindor (596019) is in the fixture as an active infielder.
    cy.get('[data-cy="roster-row"][data-cy-player-id="596019"]').click();
    cy.location("pathname").should("eq", "/player/596019");
  });

  it("click a last-game row → navigates to /game/[id]", () => {
    cy.get('[data-cy="last-game-row"][data-cy-game-id="8001"]').click();
    cy.location("pathname").should("eq", "/game/8001");
  });
});
